version: "3.7"

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/images:/usr/share/nginx/html/images/
#    expose:
#      - 80
#      - 443
    depends_on:
      - fastapi
    networks:
      - my_network

  db:
    container_name: postgres
    build:
      context: ./postgres_docker/
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - my_network

  fastapi:
    container_name: fastapi
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./nginx/images:/code/images/
    depends_on:
      - db
#    expose:
#      - 8000
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge