version: "3.7"

services:

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/images:/usr/share/nginx/html/images/

  db:
    container_name: postgres
    build:
      context: ./postgres_docker
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
#    expose:
#      - 5432
    networks:
      - default

  web:
    container_name: fastapi
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./nginx/images:/code/images/
#    expose:
#      - 8000
#    env_file:
#      - ./.env.prod
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - default

networks:
  default:
    driver: host
